### ISSUE TITLE
Optional dependencies are not picked up

### ISSUE THREAD

**Issue by DieBauer** [cb372/sbt-explicit-dependencies#47]
I'm using this plugin to sanitize my dependencies, thanks for that! 

But I'm now running into an issue that one module is using optional dependencies. 

```scala
val h2database = "com.h2database" % "h2" % "1.2.147" % "optional"
```

But this dependency now keeps on showing up in undeclared dependencies. 
I see https://github.com/cb372/sbt-explicit-dependencies/blob/b106c391713ac8a0d2b4cc9e3e2773c4ff50983d/src/main/scala/explicitdeps/Logic.scala#L99 that compile and provided scope is supported. 

Can we also support optional?

**Comment by cb372** [comment]
Yes, that seems reasonable.

I feel like I deliberately chose not to include optional dependencies, but I can't remember why... I can't think of a good reason not to include them.

Do you want to make a PR? If so, please include a scripted test for it. https://github.com/cb372/sbt-explicit-dependencies/tree/master/src/sbt-test/basic/no-unused-no-undeclared-provided is probably a good test to use as a reference.

**Comment by DieBauer** [comment]
Let me see what I can come up with!

**Comment by cb372** [comment]
@DieBauer Thanks for the PR. I'll take a look at it now.

Out of curiosity, why does your project have h2 as an optional dependency instead of a normal compile-time dependency? Is your project a library or an application? I'd like to understand more about your use case, because I haven't encountered many optional dependencies in the wild.

Do you have some kind of conditional code, along the lines of

```scala
if (h2isOnTheClasspath) {
  useH2()
}
```

?

**Comment by DieBauer** [comment]
That's exactly the use case. For me it is a spring-boot module/library, that has some classes with `@ConditionalOnClass(...)`. This effectively toggling features depending on classpath configuration.
